### ISSUE TITLE
With new .yml format, impossible to start an utterance with a slot

### ISSUE THREAD

**Issue by TiboC** [snipsco/snips-nlu#719]
Hello,
I was updating your lib and I faced an issue with your yml parser lib.
Lines for my utterances can't start with a "[" and therefore can't start with a slot
For example:

```
# Login Intent
---
type: intent
name: login
slots:
  - name: service
    entity: service
utterances:
  - log in with [service]
  - log into [service]
  - [service] login
```
This is not working:
```
yaml.parser.ParserError: while parsing a block collection
  in "nlp/data/intents/login.yml", line 9, column 3
expected <block end>, but found '<scalar>'
  in "nlp/data/intents/login.yml", line 11, column 16
```

---
```
# Login Intent
---
type: intent
name: login
slots:
  - name: service
    entity: service
utterances:
  - log in with [service]
  - log into [service]
  - a [service] login
```
This is ok

Adding a space doesn't solve the issue. Any idea on how to solve the issue ?
Thanks
Best

**Comment by adrienball** [comment]
Hi @TiboC,
Starting a string value with a `[` is indeed not valid in YAML. In these cases you have to put the value between double quotes:
```
# Login Intent
---
type: intent
name: login
slots:
  - name: service
    entity: service
utterances:
  - log in with [service]
  - log into [service]
  - "[service] login"
```

I realize we should document that as it seems to be a common source of confusion.
Best,
Adrien
